defaults: &defaults
  gmaps_api_key: ABQIAAAA5zHyazu_Llv3H_a1w9d_XhT2yXp_ZAY8_ufC3CFXhHIE1NvwkxTBZnWfXO7AdJaS6xPN3ezcz6ZHHQ
  version: 0.3
  
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  gmaps_api_key: ABQIAAAA5zHyazu_Llv3H_a1w9d_XhRpEjrOuO3noO1x0jdNNW9JykmvaxQu6DuLyyBacd_YWgPezR2Z3cXKfg
